mixed-port: 17890
allow-lan: false
mode: rule
log-level: info
ipv6: true
tcp-concurrent: true
external-controller: 127.0.0.1:19090
find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: false

proxies:
  - name: DIRECT
    type: direct
    udp: true

proxy-providers:
  default:
    type: http
    url: "__SUBSCRIPTION_URL__"
    path: ./providers/default.yaml
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: Proxy
    type: select
    use:
      - default
    proxies:
      - DIRECT

rules:
  - DOMAIN-SUFFIX,localhost,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - MATCH,Proxy
